package de.nimple.domain;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import de.nimple.domain.Contact;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table contacts.
*/
public class ContactDao extends AbstractDao<Contact, Long> {

    public static final String TABLENAME = "contacts";

    /**
     * Properties of entity Contact.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property RowId = new Property(0, Long.class, "rowId", true, "rowId");
        public final static Property Name = new Property(1, String.class, "name", false, "name");
        public final static Property Email = new Property(2, String.class, "email", false, "email");
        public final static Property TelephoneHome = new Property(3, String.class, "telephoneHome", false, "telephoneHome");
        public final static Property TelephoneMobile = new Property(4, String.class, "telephoneMobile", false, "telephoneMobile");
        public final static Property Website = new Property(5, String.class, "website", false, "website");
        public final static Property Street = new Property(6, String.class, "street", false, "street");
        public final static Property Postal = new Property(7, String.class, "postal", false, "postal");
        public final static Property City = new Property(8, String.class, "city", false, "city");
        public final static Property Company = new Property(9, String.class, "company", false, "company");
        public final static Property Position = new Property(10, String.class, "position", false, "position");
        public final static Property FacebookId = new Property(11, String.class, "facebookId", false, "facebookId");
        public final static Property FacebookUrl = new Property(12, String.class, "facebookUrl", false, "facebookUrl");
        public final static Property TwitterId = new Property(13, String.class, "twitterId", false, "twitterId");
        public final static Property TwitterUrl = new Property(14, String.class, "twitterUrl", false, "twitterUrl");
        public final static Property XingUrl = new Property(15, String.class, "xingUrl", false, "xingUrl");
        public final static Property LinkedinUrl = new Property(16, String.class, "linkedinUrl", false, "linkedinUrl");
        public final static Property Hash = new Property(17, String.class, "hash", false, "hash");
        public final static Property Created = new Property(18, Long.class, "created", false, "created");
        public final static Property Note = new Property(19, String.class, "note", false, "note");
    };


    public ContactDao(DaoConfig config) {
        super(config);
    }
    
    public ContactDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'contacts' (" + //
                "'rowId' INTEGER PRIMARY KEY ," + // 0: rowId
                "'name' TEXT," + // 1: name
                "'email' TEXT," + // 2: email
                "'telephoneHome' TEXT," + // 3: telephoneHome
                "'telephoneMobile' TEXT," + // 4: telephoneMobile
                "'website' TEXT," + // 5: website
                "'street' TEXT," + // 6: street
                "'postal' TEXT," + // 7: postal
                "'city' TEXT," + // 8: city
                "'company' TEXT," + // 9: company
                "'position' TEXT," + // 10: position
                "'facebookId' TEXT," + // 11: facebookId
                "'facebookUrl' TEXT," + // 12: facebookUrl
                "'twitterId' TEXT," + // 13: twitterId
                "'twitterUrl' TEXT," + // 14: twitterUrl
                "'xingUrl' TEXT," + // 15: xingUrl
                "'linkedinUrl' TEXT," + // 16: linkedinUrl
                "'hash' TEXT," + // 17: hash
                "'created' INTEGER," + // 18: created
                "'note' TEXT);"); // 19: note
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'contacts'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Contact entity) {
        stmt.clearBindings();
 
        Long rowId = entity.getRowId();
        if (rowId != null) {
            stmt.bindLong(1, rowId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String email = entity.getEmail();
        if (email != null) {
            stmt.bindString(3, email);
        }
 
        String telephoneHome = entity.getTelephoneHome();
        if (telephoneHome != null) {
            stmt.bindString(4, telephoneHome);
        }
 
        String telephoneMobile = entity.getTelephoneMobile();
        if (telephoneMobile != null) {
            stmt.bindString(5, telephoneMobile);
        }
 
        String website = entity.getWebsite();
        if (website != null) {
            stmt.bindString(6, website);
        }
 
        String street = entity.getStreet();
        if (street != null) {
            stmt.bindString(7, street);
        }
 
        String postal = entity.getPostal();
        if (postal != null) {
            stmt.bindString(8, postal);
        }
 
        String city = entity.getCity();
        if (city != null) {
            stmt.bindString(9, city);
        }
 
        String company = entity.getCompany();
        if (company != null) {
            stmt.bindString(10, company);
        }
 
        String position = entity.getPosition();
        if (position != null) {
            stmt.bindString(11, position);
        }
 
        String facebookId = entity.getFacebookId();
        if (facebookId != null) {
            stmt.bindString(12, facebookId);
        }
 
        String facebookUrl = entity.getFacebookUrl();
        if (facebookUrl != null) {
            stmt.bindString(13, facebookUrl);
        }
 
        String twitterId = entity.getTwitterId();
        if (twitterId != null) {
            stmt.bindString(14, twitterId);
        }
 
        String twitterUrl = entity.getTwitterUrl();
        if (twitterUrl != null) {
            stmt.bindString(15, twitterUrl);
        }
 
        String xingUrl = entity.getXingUrl();
        if (xingUrl != null) {
            stmt.bindString(16, xingUrl);
        }
 
        String linkedinUrl = entity.getLinkedinUrl();
        if (linkedinUrl != null) {
            stmt.bindString(17, linkedinUrl);
        }
 
        String hash = entity.getHash();
        if (hash != null) {
            stmt.bindString(18, hash);
        }
 
        Long created = entity.getCreated();
        if (created != null) {
            stmt.bindLong(19, created);
        }
 
        String note = entity.getNote();
        if (note != null) {
            stmt.bindString(20, note);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Contact readEntity(Cursor cursor, int offset) {
        Contact entity = new Contact( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // rowId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // email
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // telephoneHome
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // telephoneMobile
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // website
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // street
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // postal
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // city
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // company
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // position
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // facebookId
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // facebookUrl
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // twitterId
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // twitterUrl
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // xingUrl
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // linkedinUrl
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // hash
            cursor.isNull(offset + 18) ? null : cursor.getLong(offset + 18), // created
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19) // note
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Contact entity, int offset) {
        entity.setRowId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setEmail(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTelephoneHome(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTelephoneMobile(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setWebsite(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setStreet(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setPostal(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setCity(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setCompany(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setPosition(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setFacebookId(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setFacebookUrl(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setTwitterId(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setTwitterUrl(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setXingUrl(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setLinkedinUrl(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setHash(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setCreated(cursor.isNull(offset + 18) ? null : cursor.getLong(offset + 18));
        entity.setNote(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Contact entity, long rowId) {
        entity.setRowId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Contact entity) {
        if(entity != null) {
            return entity.getRowId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
